apiVersion: v1
kind: ConfigMap
metadata:
  name: coffeeshop-config
  namespace: {{ .Values.global.namespace }}
data:
  spring.profiles.active: {{ .Values.global.spring.profiles | quote }}
  aws.region: {{ .Values.global.aws.region | quote }}
  db.host: {{ .Values.global.db.host | quote }}
  db.port: {{ .Values.global.db.port | quote }}
  db.name: {{ .Values.global.db.name | quote }}
