apiVersion: v1
kind: ConfigMap
metadata:
  name: coffeeshop-config
  namespace: {{ .Values.global.namespace }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.spring.profiles | quote }}
  AWS_REGION: {{ .Values.global.aws.region | quote }}
  DB_HOST: {{ .Values.global.db.host | quote }}
  DB_PORT: {{ .Values.global.db.port | quote }}
  DB_NAME: {{ .Values.global.db.name | quote }}
